# Default configuration for I2I model training
# Usage: uv run python script/train_with_cli.py --config script/configs/default.yaml

# Model configuration
model:
  class_path: src.register_by_gen.dl_model.model_i2i.I2IModel
  init_args:
    in_channels: 1
    out_channels: 1
    lr: 0.001

# Data configuration  
data:
  class_path: src.register_by_gen.dataset.syn2023_dset.SynthRAD2023DataModule
  init_args:
    data_root: "data/syn23_pelvic"
    mode: "2d"
    patch_size: [192, 192]
    batch_size: 16
    num_workers: 4
    samples_per_volume: 20

# Trainer configuration
trainer:
  max_epochs: 50
  accelerator: auto
  devices: 1
  precision: "32-true"
  log_every_n_steps: 10
  check_val_every_n_epoch: 1
  enable_progress_bar: true
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: "logs"
      name: "i2i_cli"
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "val/loss"
        mode: "min"
        save_top_k: 3
        filename: "best-{epoch:02d}-{val_loss:.3f}"
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val/loss"
        patience: 10
        mode: "min"

# Seed for reproducibility
seed_everything: 42